ips_vigiladas:
  - "192.168.0.105"
  - "192.168.0.113"
  - "192.168.0.112"
  - "192.168.0.111"
  - "192.168.0.118"

palabras_clave:
  - "porno"
  - "sex"
  - "xxx"
  - "adult"
  - "hentai"
  - "erotic"
  - "nude"
  - "camgirl"
  - "fetish"
  - "bdsm"
  - "harcore"
  - "blowjob"
  - "dildo"
  - "masturbation"
  - "orgy"
  - "anal"
  - "milf"
  - "coje"
  - "pussy"
  - "cum"
  - "pene"
  - "tetas"
  - "culos"
  - "ass"